name = "sps_genai"
version = "0.1.0"
description = "MNIST GAN with PyTorch"
requires-python = ">=3.10"

dependencies = [
    "torch",
    "torchvision",
    "matplotlib",
    "pillow",
    "ipython"
]